### ISSUE TITLE
FR: MT Solutions Secondary PDP MT8 Hero variant

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-macktrucks-com-rd#138] opened 2023-10-23 15:02 UTC
**Agile Requirement**
Create a new Hero variant for the secondary PDP MT8 page -> https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?type=design&node-id=2243-137825&mode=dev

**Comment by DanielaPedrochevd** [comment] 2023-10-24 11:42
We should use the PDP hero, no need for a new one, the team sees no value.

**Comment by cogniSyb** [comment] 2024-02-20 15:23
Duplicate of #42

**Closed as not planned by cogniSyb** 2024-02-20 15:23 UTC
Labels: Solutions
